# Generated by Django 4.0.1 on 2022-01-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmngr', '0003_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
