# Generated by Django 4.0.1 on 2022-01-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docmngr', '0004_folder_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='docmngr.folder'),
            preserve_default=False,
        ),
    ]
