# Generated by Django 4.0.1 on 2022-01-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmngr', '0007_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
