# Generated by Django 4.0.1 on 2022-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmngr', '0008_alter_topic_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('parent_folder_id', 'name'), name='unique within parent'),
        ),
    ]
